### ISSUE TITLE
Simple test

### ISSUE THREAD

**Issue by jonaskello** [andrey-pohilko/registry-cli#25]
I'm having some trouble connecting to my gitlab registry (see #12). So I just wanted to make a simple test locally on my computer to see how it should work. So I tried this:

```
docker run -d -p 5000:5000 --name registry registry:2
docker pull ubuntu
docker tag ubuntu localhost:5000/myfirstimage
docker push localhost:5000/myfirstimage
```

Basically that just sets up a registry locally and pushes in an image (see [these instructions](https://docs.docker.com/registry/#requirements)).

Then I go ahead and try to list the images from the local registry like this:
```
docker run --rm anoxis/registry-cli -r http://localhost:5000
```
But it gives this output:

```
Traceback (most recent call last):
  File "/registry.py", line 460, in <module>
    main_loop(args)
  File "/registry.py", line 406, in main_loop
    image_list = registry.list_images()
  File "/registry.py", line 123, in list_images
    result = self.send('/v2/_catalog')
  File "/registry.py", line 108, in send
    verify = not self.no_validate_ssl)
  File "/registry.py", line 40, in request
    return requests.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /v2/_catalog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8241dfde90>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

I am probably doing something wrong, but I don't know what :-). Maybe there is some user and password that is active for a simple registry like this. But since I can push images without login I think it is a bit strange.

**Comment by andrey-pohilko** [comment]
Yeah, it took me several minutes to understand why this happens :).

The reason is very simple - when you run the script inside the docker
image, the `localhost` is the docker image itself, but not your host
machine (where your docker registry is accesible at). So, to query list of
images, you need to connect regsitry-cli to the registry image and mention
its name, not localhost:
`docker run --rm --link registry anoxis/registry-cli -r http://registry:5000
`

I tried it on my local machine and it worked.

As for the issue #12, I actually need more time to dive deeper into token
authentication and make necessary changes to the code. This will probably
take a couple of days, which I don't have at the moment, unfortunately.

**Comment by jonaskello** [comment]
Yes, that makes perfect sense :-).

I have it working now too. I think this might be worth mentioning in the readme because it is not obvious although it is very logical.
