### ISSUE TITLE
Not working with the registry of Nexus?

### ISSUE THREAD

**Issue by EugenMayer** [andrey-pohilko/registry-cli#43]
`docker run --rm anoxis/registry-cli -l XXXXX:YYYY -r https://myregsitry.public.tld -i log --delete --num 2 --dry-run`
```
Will delete all but 2 last tags
---------------------------------
Image: log
  tag: 0.0.5
  tag: 0.0.7
  tag: 0.0.6
  tag: 0.0.8
Getting digests for tags to keep:
Getting digest for tag 0.0.7
  tag digest not found: 404
Tag 0.0.7 does not exist for image log. Ignore here.
Getting digest for tag 0.0.8
  tag digest not found: 404
Tag 0.0.8 does not exist for image log. Ignore here.
  deleting tag 0.0.5
would delete tag 0.0.5
  deleting tag 0.0.6
would delete tag 0.0.6
```

Anything else we use with that docker registry just works, any client, any library and also https://github.com/mlabouardy/nexus-cli worked without an issue.

Registry is https, official LE certificate. Any hints? i always get those 404 or even 503.

**Comment by ipavlushin** [comment]
Could you make GET to https://your.registry/v2/log/manifests/0.0.7 and https://your.registry/v2/log/manifests/0.0.8 and print debug output?

**Comment by tahitianstud** [comment]
we have to same situation and were getting a 404 also

after some testing, it comes from requesting the manifest with the `HEAD` method

not sure what the impact is, but if you change the request to `GET` method instead, the script does send the right `DELETE` command

maybe there could be some `CLI` flag in order to choose the http method to use ?

**Comment by andrey-pohilko** [comment]
@tahitianstud @EugenMayer  please download new version and try with flag `--digest-method GET`
